const cthulhuSkillsList = [
	{ name: 'Accounting', id: 'acc' },
	{ name: 'Animal Handling', id: 'an_h' },
	{ name: 'Anthropology', id: 'anthr' },
	{ name: 'Appraise', id: 'appr' },
	{ name: 'Archaeology', id: 'arch' },
	{ name: 'Art/Craft (Acting)', id: 'art_cr_act' },
	{ name: 'Art/Craft (Fine Art)', id: 'art_cr_fart' },
	{ name: 'Art/Craft (Forgery)', id: 'art_cr_forg' },
	{ name: 'Art/Craft (Photography)', id: 'art_cr_ph' },
	{ name: 'Charm', id: 'char' },
	{ name: 'Climb', id: 'cl' },
	{ name: 'Credit Rating', id: 'cr_r' },
	{ name: 'Cthulhu Mythos', id: 'c_myth' },
	{ name: 'Disguise', id: 'disg' },
	{ name: 'Dodge', id: 'dod' },
	{ name: 'Drive Auto', id: 'drive_a' },
	{ name: 'Electrical Repair', id: 'el_re' },
	{ name: 'Fast Talk', id: 'fast_talk' },
	{ name: 'Fighting (Brawl)', id: 'f_brawl' },
	{ name: 'Firearms (Handgun)', id: 'fir_hand' },
	{ name: 'Firearms (Rifle/Shotgun)', id: 'fir_rif_sh' },
	{ name: 'First Aid', id: 'f_aid' },
	{ name: 'Heavy Weapons', id: 'h_weap' },
	{ name: 'History', id: 'hist' },
	{ name: 'Hypnosis', id: 'hypno' },
	{ name: 'Intimidate', id: 'intim' },
	{ name: 'Jump', id: 'jump' },
	{ name: 'Language (Own)', id: 'l_own' },
	{ name: 'Law', id: 'la' },
	{ name: 'Library Use', id: 'lib_u' },
	{ name: 'Listen', id: 'list' },
	{ name: 'Locksmith', id: 'lock' },
	{ name: 'Mechanical Repair', id: 'mech_r' },
	{ name: 'Medicine', id: 'med' },
	{ name: 'Natural World', id: 'n_wor' },
	{ name: 'Navigate', id: 'navi' },
	{ name: 'Occult', id: 'occ' },
	{ name: 'Op. Heavy Machinery', id: 'op_h_mach' },
	{ name: 'Persuade', id: 'pers' },
	{ name: 'Pilot (Aircraft)', id: 'pil_air' },
	{ name: 'Pilot (Boat)', id: 'pil_boat' },
	{ name: 'Psychology', id: 'psycholo' },
	{ name: 'Psychoanalysis', id: 'psychoana' },
	{ name: 'Read Lips', id: 'r_lip' },
	{ name: 'Ride', id: 'ri' },
	{ name: 'Science (Astronomy)', id: 'sci_astr' },
	{ name: 'Science (Botany)', id: 'sci_bt' },
	{ name: 'Science (Biology)', id: 'sci_bio' },
	{ name: 'Science (Chemistry)', id: 'sci_ch' },
	{ name: 'Science (Geology)', id: 'sci_geo' },
	{ name: 'Science (Mathematics)', id: 'sci_math' },
	{ name: 'Science (Pharmacy)', id: 'sci_pha' },
	{ name: 'Science (Physics)', id: 'sci_phy' },
	{ name: 'Science (Zoology)', id: 'sci_zoo' },
	{ name: 'Sleight of Hand', id: 's_o_h' },
	{ name: 'Spot Hidden', id: 'spt_hid' },
	{ name: 'Stealth', id: 'stealth' },
	{ name: 'Swim', id: 'sw' },
	{ name: 'Throw', id: 'thr' },
	{ name: 'Track', id: 'trk' },
];

export interface SkillType {
	name: string;
	id: string;
}

export function getSkillById(id: string) {
	return cthulhuSkillsList.find((item) => item.id === id) || null;
}

export default cthulhuSkillsList;
